services:
  - type: web
    name: rons-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YTDL_NO_UPDATE
        value: 1
      - key: SLEEP_INTERVAL
        value: 2
    plan: free
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1